name: Build and Deploy
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:
permissions:
  actions: write
  contents: write
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ startsWith(github.ref, 'refs/pull/') }}

jobs:
  release:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          cache: "gradle"
          distribution: "temurin"
          java-version: 11

      - name: Execute Gradle build
        run: chmod +x ./gradlew && ./gradlew shadowJar

      - uses: kolpav/purge-artifacts-action@v1
        if: github.event_name != 'pull_request'
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          expire-in: 0

      - uses: actions/upload-artifact@v3
        if: github.event_name != 'pull_request'
        with:
          name: build
          path: build/libs/*.jar